recipes/devel/squashfs-tools.yaml

This is needed in order for the respective changes in
BobBuildTool/basement#133 to work correctly with this layer.

devel/squashfs-tools: Use xz-utils dev package

---

recipes/libs/cairo.yaml

The cairo recipe fails with: strings: command not found
Therefore we add the binutils tools providing the strings command.
Also upgrade to the latest version that is available for direct
download at the projects website.

libs/cairo: Fix build and upgrade to 1.16.0

---

recipes/utils/e2fsprogs.yaml

Otherwise cross-compiling fails with
```
[  75] |utils::e2fsprogs| make[1]: Leaving directory '/bob/cd8e3c1ec9a5edbd24ab417832a196e1796b8768/workspace/build'
[  75] |utils::e2fsprogs| /bob/a21624a3af225641b383a26df8320bc4d2445605/workspace/config/parse-types.sh: line 116: -o: command not found
[  75] |utils::e2fsprogs| /bob/a21624a3af225641b383a26df8320bc4d2445605/workspace/config/parse-types.sh: line 117: ./asm_types: No such file or directory
[  75] |utils::e2fsprogs| rm: cannot remove 'asm_types': No such file or directory
```

utils/e2fsprogs: Add host-toolchain

---

recipes/devel/squashfs-tools.yaml

Besides a security fix for CVE-2021-41072 this upgrade brings successful compilation back to squashfs-tools, after the recent GCC upgrade broke it (see https://github.com/plougher/squashfs-tools/pull/83).

devel/squashfs-tools: Upgrade to 4.5.1

---

recipes/devel/dtc.yaml

This adds AR to the buildVars in devel/dtc, because otherwise it complains that `ar` is an unknown command.
@jkloetzke

devel/dtc: Add AR to buildVars

---

recipes/libs/cairo.yaml

The built system of cairo changed to meson.

libs/cairo: bump to version 1.18.0

---

recipes/kernel/kmod.yaml

This package actually provides libkmod which other packages on the target may want to use.
Also bump to version 33.

kernel/kmod: add dev/tgt variants

---

classes/rootfs.yaml
recipes/core/busybox.yaml
recipes/net/openssh.yaml
recipes/utils/screen.yaml
recipes/virt/libjpeg.yaml

Search for *.shell-table files in the .bob directories and cat them into one /etc/shells. Some login tools check for the existence of an entry for the used shell in /etc/shells. Packages which provide shells, can simply create such a file with an appropriate entry.

rootfs: add shell-tables + fixes

---

recipes/net/openssh.yaml

Since glibc 2.39 it doesn't come with a libcrypt anymore. This means sshd had no support for password decryption methods beside md5 and openssl des.
This broke sshd login support e.g. with the rootfs support class, because this uses sha-512 encryption of the user passwords.
Fix this by adding libxcrypt as dependency which provides this functionality to openssh again.

net::openssh: add libxcrypt dependency

---

recipes/core/busybox.yaml

Leave the build-dir before generating the user table files to fix
```
+ mkdir -p install/.bob
+ grep -qE '^CONFIG_FEATURE_SUID=y$' build/.config grep: build/.config: No such file or directory
+ printf '/bin/sh\n/usr/bin/sh\n'
+ grep -qE '^CONFIG_SHELL_ASH=y$' build/.config grep: build/.config: No such file or directory
+ grep -qE '^CONFIG_SHELL_HUSH=y$' build/.config grep: build/.config: No such file or directory #
++ bob_handle_error 2
```
build-error.

core::busybox: fix build error

---

classes/rootfs.yaml
classes/rootfs/ext4.yaml

There a multiple use cases on how to set the final image size. One may not care at all, others may want to specify a certain percentage of free space and than others may want to specify the exact size. Those different use cases can now be expressed with the following:
$3: output size (optional)
This can be:
- nothing: auto calc size + head room (18%)
- number:  absolute overall size in kbytes
- number%: percentage in the form of 1.20% to add 20%
- number+: absolute free space in kbytes in the form of 1024+ to add 1MB

classes::rootfs::ext4: make size handling more versatile

---

recipes/utils/e2fsprogs.yaml
recipes/utils/e2fsprogs/0001-e2fsprogs-resize-resource-track.patch
recipes/utils/e2fsprogs/0002-e2fsprogs-disable-resource-tracking-l4re.patch

Further guard the resource tracking feature of e2fsprogs and disable its usage such that no calls to sbrk() are emitted. sbrk() is not universally available on all environments.

utils/e2fsprogs: Avoid sbrk() usage

---

recipes/libs/libxslt.yaml

Disable use of crypto as gcrypt to avoid using the host gcrypt library when building without sandbox.

libxslt: explicit disable crypto

---

recipes/devel/dtc.yaml
recipes/kernel/linux.yaml
recipes/libs/elfutils.yaml
recipes/libs/libnl.yaml
recipes/libs/libpcap.yaml
recipes/libs/libxkbcommon.yaml
recipes/libs/mesa3d.yaml
recipes/libs/nettle.yaml
recipes/libs/pcre2.yaml
recipes/multimedia/gstreamer.yaml
recipes/utils/acpica.yaml
recipes/utils/uboot-tools.yaml

Adapt to [basement change](https://github.com/BobBuildTool/basement/pull/247) where m4 is no longer available in the sandbox and add m4 to the buildTools as needed.

treewide: use m4 tool

---

recipes/libs/cloog.yaml
recipes/libs/libb2.yaml
recipes/utils/brtools.yaml
recipes/utils/cpio.yaml
recipes/utils/genext2fs.yaml
recipes/utils/pciutils.yaml
recipes/utils/tidy.yaml
recipes/utils/uboot-tools.yaml

Just a view fixes for failing packages. 
@sixtyfourktec : Can you please have a look on the u-boot change? I disabled the `bmp_logo` tool unconditionally, maybe we need a more fine-grained solution.

Fix some packages

---

classes/rootfs/vfat.yaml

We following a certain naming scheme, which usual has the class name in the function name.

rootfs::vfat: fix naming

---

recipes/net/iproute2.yaml

Add a recipe to build iproute2 tools.

net/iproute2: recipe to build iproute2 tools

---

recipes/libs/libyaml.yaml
recipes/python/cython.yaml
recipes/python/pyyaml.yaml

Fixes the AArch64 build failure in #57...

Fix pyyaml cross compilation

---

classes/rootfs/cpio.yaml
classes/rootfs/ext4.yaml
classes/rootfs/tar.yaml
classes/rootfs/vfat.yaml

@sixtyfourktec This failed for me on Debian without sandbox where `/usr/bin/sh` is a symlink to `dash`...

rootfs: use bash in fakeroot environment

---

recipes/python/regex.yaml

depends on https://github.com/BobBuildTool/basement/pull/253 for x86 cross compilation

Add recipe for python3 regex package v2025.2.13

---

recipes/bsp/grub2.yaml

Also for the tools we can't strip the grub2 modules. Otherwise e.g. grub-mkimage produces an unusable binary.
In addition unify the normal target and tools step. Do a prober install of the package, however, treat the modules directory differently.

bsp::grub2: unify tools/tgt package step

---

recipes/libs/libb2.yaml

Instead of specifying x86 CPU features manually, rely on the compiler built-in macros. They can be controlled by setting the right -march= and/or -mcpu= switches via the CROSS_TOOLCHAIN_ARCH and CROSS_TOOLCHAIN_CPU variables.

libs::libb2: simplify cross compilation

---

recipes/bsp/grub2.yaml

The default https://git.savannah.gnu.org/git/gnulib.git is quite slow sometimes (196.00 KiB/s atm), and returned HTTP 502 from time to time the last few weeks.
Therefore allow to override `default_gnulib_url` in `bootstrap` via `GNULIB_URL` env variable.

bsp::grub2: Make GNULIB_URL overridable

---

recipes/core/cronie.yaml

Cronie contains the standard UNIX daemon crond that runs specified programs at scheduled times and related tools. It is based on the original cron and has security and configuration enhancements like the ability to use pam and SELinux.

add recipie for cronie, a cron daemon

---

recipes/bsp/grub2.yaml

Required to make the git checkout deterministic in all cases.
Consider the following. If the bob workspace is clean (i.e. fresh checkout), the following sequence happens with regards to bsp::grub2:
```
checkout_scm
update_config
bootstrap # checks out gnulib
```
This leads to an as-is gnulib/build-aux/config.guess because it is checked out after update_config is run. If on the other hand dev/src/bsp/grub2 is not removed completely but bob still updates the workspace (e.g. after a git clean -dxf in the toplevel recipes directory), updateConfigAllRecursive will update the config files in the existing gnulib directory as well, resulting in a diff to the previous variant and therefore to an indeterministic SCM checkout.
To solve this, set APPLY_UPDATE_CONFIG to "no" and call …

bsp::grub2: Call updateConfigAllRecursive manually

---

recipes/bsp/rpi-firmware.yaml

Right now only the rpi4 files are supported. Support for other variants can be added later.

Add bsp::rpi-firmware v1.20250430

---

.pre-commit-config.yaml

We don't want to spell-check any other files that may be included by recipes.

pre-commit: only sanitize yaml files

---

classes/linux/kmod-dist.yaml

Newer scripts check for CC != HOSTCC to detect cross compilation. If detected they rebuild the host tools for the target, because the result of install-extmod-build is likely to be executed on the target (e.g. they create .deb packages). This is of course not the case for us, so fake it by unsetting them. This is not a problem because normally nothing for the target gets compiled.

classes/linux-kmod-dist: fix host tools rebuild

---

recipes/libs/botan/0001-enable-l4re.patch

On L4Re, libdl must be linked explicitly, like on most other operating systems.

libs::botan: update L4Re patch
